### ISSUE TITLE
Unable to import module

### ISSUE THREAD

**Issue by asdf1nit** [adp162/alexa-vera-bridge#5]
Your Documentation is very good but does leave a few things out. I think I've got most of it worked out but I keep getting the message: "Unable to import module 'client': No module named Crypto.Cipher" in CloudWatch.
Obviously vera is making the request but I think the problem is in avbmsg.py? 

In the amazon developer portal under test, service simulator I get a different error: 
"The remote endpoint could not be called, or the response it returned was invalid"
And when hovering over the red X on lambda response I get: "Parse error o line 1"

On the enter Utterance line I entered: "to turn on scene 23"
The lambda request is:
{
  "session": {
    "sessionId": "SessionId.b6618309-79fc-4d6a-b396-24ec0d74adee",
    "application": {
      "applicationId": "amzn1.ask.skill.ee3a9114-8e78-4393-8a75-9dd86bc25fa1"
    },
    "attributes": {},
    "user": {
      "userId": "amzn1.ask.account.AGFYMLKJM4YUBDABK3VXVAQLWO3Z7EFZW5UAQOKIMUULZINVWPV4W2J6MOL52HDBESZ5CD42QKL5LTM3OXWYQJRTATW5JQX324JRF7ZIQYJCWMOUAOMTLOEM2QSNUFUCQKUGA57CNDNRXWKSHO5HLIQ4MU6K3PZPLMOPK23RE5JY6TQHH3KZEP5H3GLDZQQXXYSRPCWTKOUYZFQ"
    },
    "new": true
  },
  "request": {
    "type": "IntentRequest",
    "requestId": "EdwRequestId.c61482ac-dd17-4035-a112-3135bbc97d0a",
    "locale": "en-US",
    "timestamp": "2017-01-04T02:21:24Z",
    "intent": {
      "name": "RunSceneIntent",
      "slots": {
        "Scene": {
          "name": "Scene",
          "value": "23"
        }
      }
    }
  },
  "version": "1.0"
}

After this request, back in CloudWatch, the logs report the same error as the first one mentioned above.

Any help is appreciated. I'm a noob to alexa and python. (been a microsoft guy for to long)
Thanks for the project!

**Comment by adp162** [comment]
Hey,

Ya, the project has evolved a little past the documentation.  When you get
the unable to import module client error what were you trying to do?
Python has a path it uses to search for modules that it gets from the
environment variable PYTHONPATH.  If you look at the comment in
test_client.py it kind of explains it.  Basically you have to add the
directory where client.py is.  But that shouldn't be needed for normal
operation (it was just some test code).

For the Crypto module error you need to install that module - it's called
pycrypto.  If you're using a recent version of Python you can just use pip
(e.g. "pip install pycrypto").  It's a little more work to get that working
from lambda though.

Let me know if you're still stuck and I can help troubleshoot.  Thanks for
playing around with it!

Andrew

**Comment by asdf1nit** [comment]
from the echo I'm just calling commands per the documentation and my device names. 

As for the PYTHONPATH yes it is imported into the path as test_client.py explains.
here is the stdout from running python test_client.py

in /home/pi/Documents/awsFiles/alexa-vera-bridge-master/server
changed to /home/pi/Documents/awsFiles/alexa-vera-bridge-master/lambda
Running test #1
configuring client security profile as "ssl_mutual_auth"
using PSK from psk.bin
Traceback (most recent call last):
  File "test_client.py", line 168, in <module>
    main()
  File "test_client.py", line 95, in main
    send_data(data)
  File "test_client.py", line 34, in send_data
    (socket, msg) = client.open_connection_to_vera()
  File "/home/pi/Documents/awsFiles/alexa-vera-bridge-master/lambda/client.py", line 183, in open_connection_to_vera
    context.load_cert_chain(certfile=cert, keyfile=key)
IOError: [Errno 2] No such file or directory

pycrypto is already installed on the rPi and at the latest version. I'd like to get this on lambda as well so I have secure communication( documentation didn't mention extra steps to get it working). FWIW my pi is in another network then the vera but my pfsense logs don't show any blocked traffic, and communication for everything else I have set up is fine. I've added a rule to pass between. All keys are proper, and running security_test.py checks fine.

This project is exactly what I'm looking for because the python server. I have several python functions I want to add for controlling other devices that my vera can't, and control my vera devices as well. I've got other voice control projects set up that work but this look's awesome and also serves for me learning more python client-server communication methods with security!

**Comment by adp162** [comment]
Ah ok, so from that trace it looks like it can't find one of the files for the ssl context.  test_client is a little hacky in that it copies some of the cert files to the local directory so that the settings in client.cfg are right.

    # Temporarily copy sample security assets to lambda directory
    copyfile('../security/sample/rootCA.pem', './rootCA.pem')
    copyfile('../security/sample/client.crt', './client.crt')
    copyfile('../security/sample/client.key', './client.key')
    copyfile('../security/sample/psk.bin', './psk.bin')

So if you set client.cfg to use other files (which you should unless you're testing) then this might fail.

Regarding the security, a mutually authenticated ssl session is really all you need.  The symmetric key encryption was just me playing around and doesn't actually add anything to security.

If you do want to play around with getting external python packages working in a lambda context check out this link: http://docs.aws.amazon.com/lambda/latest/dg/lambda-python-how-to-create-deployment-package.html.  They use virtualenv which is a good way to manage dependencies in Python, but you can do what they do manually as well.  A python package is just a .py file that gets put somewhere Python can find it.  So for pycrypto there is a file in the default Python package directory called Crypto.py.  All you have to do is copy this to the zip you upload to lambda and it should work.

**Comment by adp162** [comment]
Assuming this fixed the problem.
